package TrainApp;

/**
* TrainApp/AirconditionerExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from exercise_7.2.2.idl
* Dienstag, 20. Juni 2017 15:22 Uhr MESZ
*/

public final class AirconditionerExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public TrainApp.AirconditionerException value = null;

  public AirconditionerExceptionHolder ()
  {
  }

  public AirconditionerExceptionHolder (TrainApp.AirconditionerException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TrainApp.AirconditionerExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TrainApp.AirconditionerExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TrainApp.AirconditionerExceptionHelper.type ();
  }

}
