package TrainApp;


/**
* TrainApp/CheapTrain.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from exercise_7.2.2.idl
* Dienstag, 20. Juni 2017 15:22 Uhr MESZ
*/

public interface CheapTrain extends CheapTrainOperations, TrainApp.Train, org.omg.CORBA.portable.IDLEntity 
{
} // interface CheapTrain
