package TrainApp;


/**
* TrainApp/IllegalSpeedException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./exercise_7.2.2.idl
* Dienstag, 27. Juni 2017 12:04 Uhr MESZ
*/

public final class IllegalSpeedException extends org.omg.CORBA.UserException
{
  public int currentSpeed = (int)0;
  public int increment = (int)0;

  public IllegalSpeedException ()
  {
    super(IllegalSpeedExceptionHelper.id());
  } // ctor

  public IllegalSpeedException (int _currentSpeed, int _increment)
  {
    super(IllegalSpeedExceptionHelper.id());
    currentSpeed = _currentSpeed;
    increment = _increment;
  } // ctor


  public IllegalSpeedException (String $reason, int _currentSpeed, int _increment)
  {
    super(IllegalSpeedExceptionHelper.id() + "  " + $reason);
    currentSpeed = _currentSpeed;
    increment = _increment;
  } // ctor

} // class IllegalSpeedException
