package TrainApp;


/**
* TrainApp/PremiumTrainOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./exercise_7.2.2.idl
* Dienstag, 27. Juni 2017 12:04 Uhr MESZ
*/

public interface PremiumTrainOperations  extends TrainApp.TrainOperations
{
  String name ();
  void setTemperature (org.omg.CORBA.FloatHolder temperature) throws TrainApp.AirconditionerException;
  void setDiffuseLightBrightness (org.omg.CORBA.FloatHolder brightness);
  void setChilloutMusic (float audioData);
} // interface PremiumTrainOperations
