package TrainApp;


/**
* TrainApp/PremiumTrainHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from exercise_7.2.2.idl
* Dienstag, 20. Juni 2017 15:22 Uhr MESZ
*/

abstract public class PremiumTrainHelper
{
  private static String  _id = "IDL:TrainApp/PremiumTrain:1.0";

  public static void insert (org.omg.CORBA.Any a, TrainApp.PremiumTrain that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static TrainApp.PremiumTrain extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (TrainApp.PremiumTrainHelper.id (), "PremiumTrain");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static TrainApp.PremiumTrain read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_PremiumTrainStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, TrainApp.PremiumTrain value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static TrainApp.PremiumTrain narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TrainApp.PremiumTrain)
      return (TrainApp.PremiumTrain)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      TrainApp._PremiumTrainStub stub = new TrainApp._PremiumTrainStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static TrainApp.PremiumTrain unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TrainApp.PremiumTrain)
      return (TrainApp.PremiumTrain)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      TrainApp._PremiumTrainStub stub = new TrainApp._PremiumTrainStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
