package TrainApp;


/**
* TrainApp/PremiumTrain.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./exercise_7.2.2.idl
* Dienstag, 27. Juni 2017 12:04 Uhr MESZ
*/

public interface PremiumTrain extends PremiumTrainOperations, TrainApp.Train, org.omg.CORBA.portable.IDLEntity 
{
} // interface PremiumTrain
