package TrainApp;


/**
* TrainApp/SevereMalfunctionException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from exercise_7.2.2.idl
* Dienstag, 20. Juni 2017 15:22 Uhr MESZ
*/

public final class SevereMalfunctionException extends org.omg.CORBA.UserException
{
  public short errors = (short)0;

  public SevereMalfunctionException ()
  {
    super(SevereMalfunctionExceptionHelper.id());
  } // ctor

  public SevereMalfunctionException (short _errors)
  {
    super(SevereMalfunctionExceptionHelper.id());
    errors = _errors;
  } // ctor


  public SevereMalfunctionException (String $reason, short _errors)
  {
    super(SevereMalfunctionExceptionHelper.id() + "  " + $reason);
    errors = _errors;
  } // ctor

} // class SevereMalfunctionException
