package TrainApp;


/**
* TrainApp/TrainStatusHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./exercise_7.2.2.idl
* Dienstag, 27. Juni 2017 12:04 Uhr MESZ
*/

abstract public class TrainStatusHelper
{
  private static String  _id = "IDL:TrainApp/TrainStatus:1.0";

  public static void insert (org.omg.CORBA.Any a, TrainApp.TrainStatus that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static TrainApp.TrainStatus extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (TrainApp.TrainStatusHelper.id (), "TrainStatus", new String[] { "new", "good", "okay", "bad"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static TrainApp.TrainStatus read (org.omg.CORBA.portable.InputStream istream)
  {
    return TrainApp.TrainStatus.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, TrainApp.TrainStatus value)
  {
    ostream.write_long (value.value ());
  }

}
