package TrainApp;

/**
* TrainApp/TrainStatusHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from exercise_7.2.2.idl
* Dienstag, 20. Juni 2017 15:22 Uhr MESZ
*/

public final class TrainStatusHolder implements org.omg.CORBA.portable.Streamable
{
  public TrainApp.TrainStatus value = null;

  public TrainStatusHolder ()
  {
  }

  public TrainStatusHolder (TrainApp.TrainStatus initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TrainApp.TrainStatusHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TrainApp.TrainStatusHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TrainApp.TrainStatusHelper.type ();
  }

}
