package TrainApp;


/**
* TrainApp/TrainHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./exercise_7.2.2.idl
* Dienstag, 27. Juni 2017 12:04 Uhr MESZ
*/

abstract public class TrainHelper
{
  private static String  _id = "IDL:TrainApp/Train:1.0";

  public static void insert (org.omg.CORBA.Any a, TrainApp.Train that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static TrainApp.Train extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (TrainApp.TrainHelper.id (), "Train");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static TrainApp.Train read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_TrainStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, TrainApp.Train value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static TrainApp.Train narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TrainApp.Train)
      return (TrainApp.Train)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      TrainApp._TrainStub stub = new TrainApp._TrainStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static TrainApp.Train unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TrainApp.Train)
      return (TrainApp.Train)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      TrainApp._TrainStub stub = new TrainApp._TrainStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
