package hindenbug.HelloApp;


/**
* hindenbug/HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* Montag, 19. Juni 2017 20:01 Uhr MESZ
*/

public interface HelloOperations 
{
  String sayHello ();
  void shutdown ();
} // interface HelloOperations
