package hindenbug.HelloApp;

/**
* hindenbug/HelloApp/HelloHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* Montag, 19. Juni 2017 20:01 Uhr MESZ
*/

public final class HelloHolder implements org.omg.CORBA.portable.Streamable
{
  public hindenbug.HelloApp.Hello value = null;

  public HelloHolder ()
  {
  }

  public HelloHolder (hindenbug.HelloApp.Hello initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = hindenbug.HelloApp.HelloHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    hindenbug.HelloApp.HelloHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return hindenbug.HelloApp.HelloHelper.type ();
  }

}
