package hindenbug.HelloApp;


/**
* hindenbug/HelloApp/Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* Montag, 19. Juni 2017 20:01 Uhr MESZ
*/

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
