<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="exercise_2_2" nsURI="http://www.example.org/exercise_2_2" nsPrefix="exercise_2_2">
  <eClassifiers xsi:type="ecore:EClass" name="Forum">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentForum" eType="#//Forum"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="threads" upperBound="-1"
        eType="#//Thread" eOpposite="#//Thread/forum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="moderator" eType="#//Moderator"
        eOpposite="#//Moderator/moderates"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User">
    <eStructuralFeatures xsi:type="ecore:EReference" name="uses" upperBound="-1" eType="#//Forum"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="username" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="posts" upperBound="-1"
        eType="#//Post" eOpposite="#//Post/author"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Moderator" eSuperTypes="#//User">
    <eStructuralFeatures xsi:type="ecore:EReference" name="moderates" upperBound="-1"
        eType="#//Forum" eOpposite="#//Forum/moderator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Thread">
    <eStructuralFeatures xsi:type="ecore:EReference" name="forum" lowerBound="1" eType="#//Forum"
        eOpposite="#//Forum/threads"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSticky" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="post" lowerBound="1" upperBound="-1"
        eType="#//Post"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Post">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="send" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="author" lowerBound="1"
        eType="#//User" eOpposite="#//User/posts"/>
  </eClassifiers>
</ecore:EPackage>
